version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: solana_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: solana_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: solana_app
    restart: always
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://admin:password@postgres:5432/solana_db
    ports:
      - "3000:3000"

volumes:
  pg_data:
